name: technical_test_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  dropdown_search: ^6.0.1
  go_router: ^16.2.5

  # State
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7
  get_it: ^8.0.0


  # Persistency
  sqflite: ^2.3.3+1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.9.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.0
  integration_test:
    sdk: flutter  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/json/country.json
